set(CMAKE_C_COMPILER gcc CACHE STRING "C Compiler")
set(CMAKE_CXX_COMPILER g++ CACHE STRING "CXX Compiler")
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER} CACHE STRING "ASM Compiler")

add_compile_options(
    "$<$<COMPILE_LANGUAGE:CXX>:${COMPILE_CXX_FLAGS}>"
)

set(COMPILE_C_FLAGS "-DSPLE_TESTABLE_STATIC=")
add_compile_options(
    "$<$<COMPILE_LANGUAGE:C>:${COMPILE_C_FLAGS}>"
)
