from pathlib import Path
from typing import Any, Optional

from py_app_dev.core.exceptions import UserNotificationException
from pypeline.domain.external_project import ExternalProject
from yanga.cmake.generator import CMakeGenerator
from yanga.cmake.cmake_backend import CMakeComment, CMakeContent, CMakeElement, CMakeCustomCommand, CMakeCommand, CMakePath, CMakeBuildEvent
from yanga_core.domain.execution_context import ExecutionContext

BSP_PROJECT_NAME = "aurix-tc375-bsp"
# The mirror keeps upstream's directory verbatim in a subfolder of the same name;
# only this repository's own README/upstream.json live above it.
BSP_SUBDIR = "Blinky_LED_1_KIT_TC375_SB"
LINKER_SCRIPT = f"{BSP_SUBDIR}/Lcf_Gnuc_Tricore_Tc.lsl"


def locate_bsp(execution_context: ExecutionContext) -> Path:
    """Resolve the mirrored Infineon BSP from the data registry, so the (revision-scoped) install layout stays an internal detail."""
    for project in execution_context.data_registry.find_data(ExternalProject):
        if project.name == BSP_PROJECT_NAME:
            return project.path
    raise UserNotificationException(
        f"Dependency '{BSP_PROJECT_NAME}' was not installed by a WestInstall step (no matching ExternalProject in the data registry)."
    )


class TricoreLinkerScriptCMakeGenerator(CMakeGenerator):
    """
    Point the linker at the TC375 memory map that ships with the BSP.

    This is not in the CMake toolchain file because the BSP's install path is
    revision-scoped and only known here, and copying the script into the platform
    would mean maintaining a second copy of it.
    """

    def __init__(self, execution_context: ExecutionContext, output_dir: Path, config: Optional[dict[str, Any]] = None) -> None:
        super().__init__(execution_context, output_dir, config)

    def generate(self) -> list[CMakeElement]:
        linker_script = locate_bsp(self.execution_context) / LINKER_SCRIPT
        if not linker_script.is_file():
            raise UserNotificationException(f"Linker script not found in '{BSP_PROJECT_NAME}': {linker_script}")
        return [
            CMakeComment(f"Generated by {self.__class__.__name__}"),
            # target_link_options, not add_link_options: this runs after the executable
            # is declared, and directory-scoped options would no longer apply to it.
            CMakeContent(f'target_link_options(${{PROJECT_NAME}} PRIVATE "-T{CMakePath(linker_script).to_string()}")'),
        ]


class CreateTricoreHexCMakeGenerator(CMakeGenerator):
    """Emit the ELF -> Intel HEX post-build step. Every AURIX flashing tool takes .hex."""

    def __init__(self, execution_context: ExecutionContext, output_dir: Path, config: Optional[dict[str, Any]] = None) -> None:
        super().__init__(execution_context, output_dir, config)

    def generate(self) -> list[CMakeElement]:
        elements: list[CMakeElement] = []
        elements.append(CMakeComment(f"Generated by {self.__class__.__name__}"))
        artifacts_locator = self.execution_context.create_artifacts_locator()
        variant_build_dir = CMakePath(artifacts_locator.variant_build_dir)
        variant_name = self.execution_context.variant_name or "default"
        link_out_file = variant_build_dir.joinpath(f"{variant_name}.elf")
        link_hex_file = variant_build_dir.joinpath(f"{variant_name}.hex")
        custom_command = CMakeCustomCommand(
            description="Converting ELF to HEX: ${PROJECT_NAME}.hex",
            target="${PROJECT_NAME}",
            build_event=CMakeBuildEvent.POST_BUILD,
            byproducts=[link_hex_file],
            commands=[
                CMakeCommand(
                    command="${CMAKE_OBJCOPY}",
                    arguments=["-O", "ihex", link_out_file, link_hex_file],
                )
            ],
            outputs=[],
            depends=[],
        )
        elements.append(custom_command)

        return elements
