# Generated by Transformer
string(REPLACE "\\" "/" COMPILER_PATH "$ENV{${COMPILER_NAME}_ROOT}")
set(CMAKE_C_COMPILER "${COMPILER_PATH}/ctc/bin/cctc.exe")
set(CMAKE_CXX_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
# Dependency files for incremental builds
set(CMAKE_DEPFILE_FLAGS_C "--dep-file=<DEP_FILE>")
set(CMAKE_DEPFILE_FLAGS_ASM "--dep-file=<DEP_FILE>")
set(CMAKE_C_DEPFILE_EXTENSION_REPLACE 1)
set(CMAKE_ASM_DEPFILE_EXTENSION_REPLACE 1)
# No compiler check during configure
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
# We have to use response files due to too many include paths
set(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS TRUE)
set(CMAKE_C_RESPONSE_FILE_FLAG "--option-file ")
set(CMAKE_C_RESPONSE_FILE_LINK_FLAG "--option-file ")
set(CMAKE_NINJA_FORCE_RESPONSE_FILE TRUE)
# Correct extension for linkable static libraries
set(CMAKE_STATIC_LIBRARY_SUFFIX_C ".a")

if (VARIANT_C_FLAGS)
    set(COMPILE_C_FLAGS ${VARIANT_C_FLAGS})
else()
    set(COMPILE_C_FLAGS --core=tc1.6.2 --iso=99 -OaceFgIklMnopRsUvwy --eabi=+no-clear -AGKpvX --switch=auto --integer-enumeration --default-near-size=0 --fp-model=1 --debug-info)
endif()

if (VARIANT_ASM_FLAGS)
    set(COMPILE_ASM_FLAGS ${VARIANT_ASM_FLAGS})
else()
    set(COMPILE_ASM_FLAGS --core=tc1.6.2 --list-format=1 --optimize=gs)
endif()

add_compile_options(
    "$<$<COMPILE_LANGUAGE:C>:${COMPILE_C_FLAGS}>"
    "$<$<COMPILE_LANGUAGE:ASM>:${COMPILE_ASM_FLAGS}>"
)

if (VARIANT_LINK_FLAGS)
    add_link_options(${VARIANT_LINK_FLAGS})
else()
    add_link_options(-OcLtXY --core=mpe:vtc -v --output=./link_out.hex:IHEX:4,linear --map-file=link_out.map -lcs_fpu -lfp_fpu -lrt)
endif()

add_link_options(--lsl-file=${VARIANT_LINKER_FILE})

set(CMAKE_C_LINK_EXECUTABLE "${CMAKE_C_COMPILER} -o <TARGET> <OBJECTS> <LINK_FLAGS>")
