[project]
name = "spled"
version = "0.0.1"
description = "SPL demo project"
authors = [{ name = "Avengineers" }]
requires-python = "<3.12,>=3.11"

dependencies = [
    "spl-core>=7,<8",
    "sple-static-analysis-extension>=1.8.0,<2",
    "pypeline-runner>=1,<2",
    "pytest>=8,<9",
    "pip_system_certs>=4.0,<5",
]

[tool.poetry]
package-mode = false

[[tool.poetry.source]]
name = "marquardt-pypi"
url = "https://artifactory.marquardt.de/artifactory/api/pypi/aspl-pypi-release-virtual/simple"
priority = "primary"
