# Generated by Transformer
string(REPLACE "\\" "/" COMPILER_PATH "$ENV{${COMPILER_NAME}_ROOT}")
set(CMAKE_C_COMPILER "${COMPILER_PATH}/ccppc.exe")
set(CMAKE_CXX_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_ASM_COMPILER "${COMPILER_PATH}/ccppc.exe")
set(CMAKE_DEPFILE_FLAGS_C --make_depends)
set(CMAKE_DEPFILE_FLAGS_ASM --make_depends)
set(CMAKE_C_DEPFILE_EXTENSION_REPLACE 1)
set(CMAKE_ASM_DEPFILE_EXTENSION_REPLACE 1)

set(COMPILE_C_FLAGS -vle -DC_ENABLE_INSTRUCTION_SET_VLE -D__vle --prototype_warnings -Ospeed -Wundef -Wimplicit-int -Wshadow -Wtrigraphs --prototype_errors -g -dual_debug -cpu=core_ppce200z425 -noobj -inline_prologue -pragma_asm_inline -noSPE --no_exceptions --no_commons -nokeeptempfiles -pnone --incorrect_pragma_warnings --slash_comment --long_long -nostdlib -preprocess_assembly_files -D__ghs__ -DCPP_VERSIONCHECK -DGHS -list -passsource -DBRS_DERIVATIVE_SPC58NG84 -DBRS_OSC_CLK=32 -DBRS_TIMEBASE_CLOCK=180 -DBRS_OS_USECASE_OSGEN7 -DBRS_EVA_BOARD_VEBN01620 -DBRS_PLATFORM_SPC58xx -DBRS_COMP_GHS -DBRSHW_INSTRUCTION_SET_VLE -DBRSHW_CPU_NO_OF_CORES=3 -DUSE_FBLB003=1 -DSFDC_NO_EB_STDLIB -Ospeed -c99 -G)
set(COMPILE_ASM_FLAGS -cpu=core_ppce200z425 -vle -preprocess_assembly_files -DBRS_COMP_GHS -g -Ospeed -c99 -G)
add_compile_options(
    "$<$<COMPILE_LANGUAGE:C>:${COMPILE_C_FLAGS}>"
    "$<$<COMPILE_LANGUAGE:ASM>:${COMPILE_ASM_FLAGS}>"
)
add_link_options(-overlap_warn --preprocess_linker_directive -Manx -nostdlib -keepmap -Ospeed -L${COMPILER_PATH}/lib/ppcvle -lansi -lind -larch -lmath -lstartup)
