components:
  - name: main
    path: components/main
    sources:
      - src/main.c
    required_components:
      - os
  - name: rte
    path: components/rte
    sources:
      - src/rte.c
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - components_keyboard_interface
  - name: os
    path: components/os
    sources:
      - src/os.c
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - components_spled
  - name: components_spled
    path: components/spled
    sources:
      - src/spled.c
    test_sources:
      - test/test_spled.cc
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - console_interface
      - components_keyboard_interface
      - components_light_controller
      - components_main_control_knob
      - components_power_button
      - components_power_signal_processing
      - rte
  - name: components_power_signal_processing
    path: components/power_signal_processing
    docs_sources:
      - doc/index.md
    sources:
      - src/power_signal_processing.c
    test_sources:
      - test/test_power_signal_processing.cc
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - rte
  - name: components_power_button
    path: components/power_button
    docs_sources:
      - doc/index.md
    sources:
      - src/power_button.c
    test_sources:
      - test/test_power_button.cc
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - rte
  - name: components_light_controller
    path: components/light_controller
    docs_sources:
      - doc/index.md
    sources:
      - src/light_controller.c
    test_sources:
      - test/test_light_controller.cc
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - rte
  - name: components_keyboard_interface
    path: components/keyboard_interface
    sources:
      - src/keyboard_interface.c
    include_directories:
      - path: src
        scope: PUBLIC
  - name: console_interface
    path: components/console_interface
    sources:
      - src/console_interface.c
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - rte
  - name: components_main_control_knob
    path: components/main_control_knob
    docs_sources:
      - doc/index.md
    sources:
      - src/main_control_knob.c
    test_sources:
      - test/test_main_control_knob.cc
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - rte
  - name: components_brightness_controller
    path: components/brightness_controller
    sources:
      - src/brightness_controller.c
    test_sources:
      - test/test_brightness_controller.cc
    include_directories:
      - path: src
        scope: PUBLIC
    required_components:
      - rte

variants:
  - name: Disco
    description: Disco light.
    components:
      - main
      - rte
      - os
      - components_spled
      - components_power_button
      - components_power_signal_processing
      - components_light_controller
      - components_keyboard_interface
      - console_interface
      - components_main_control_knob
      - components_brightness_controller
    features_selection_file: "variants/Disco/config.txt"

platforms:
  - name: win_exe
    description: Build Windows executable with clang
    cmake_generators:
      - step: CreateExecutableCMakeGenerator
        module: yanga.cmake.create_executable
      - step: CppCheckCMakeGenerator
        module: yanga.cmake.cppcheck
      - step: ReportCMakeGenerator
        module: yanga.cmake.reports
    toolchain_file: tools/toolchains/clang/toolchain.cmake
    is_default: true
  - name: gtest
    description: Build and run components GTest tests
    cmake_generators:
      - step: GTestCMakeGenerator
        module: yanga.cmake.gtest
        config:
            mocking:
              enabled: true
              strict: false
              exclude_symbol_patterns:
                - "_*"
      - step: CppCheckCMakeGenerator
        module: yanga.cmake.cppcheck
      - step: ReportCMakeGenerator
        module: yanga.cmake.reports
    toolchain_file: tools/toolchains/gcc/toolchain.cmake
    west_manifest:
      remotes:
        - name: gtest
          url-base: https://github.com/google
      projects:
        - name: googletest
          remote: gtest
          revision: v1.16.0
          path: gtest
    scoop_manifest:
      buckets:
        - name: main
          source: https://github.com/ScoopInstaller/Main
      apps:
        - name: graphviz
          source: main


pipeline:
  install:
    - step: CreateVEnv
      module: pypeline.steps.create_venv
      config:
        bootstrap_script: .bootstrap/bootstrap.py
        python_executable: python311
    - step: ScoopInstall
      module: yanga.steps.scoop_install
      description: Install scoop dependencies
      timeout_sec: 120
    - step: GenerateEnvSetupScript
      module: pypeline.steps.env_setup_script
    - step: WestInstall
      module: yanga.steps.west_install
      description: Install west dependencies
  gen:
    - step: KConfigGen
      module: yanga.steps.kconfig_gen
  build:
    - step: GenerateBuildSystemFiles
      module: yanga.steps.execute_build
    - step: ExecuteBuild
      module: yanga.steps.execute_build
