name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  test:
    name: CI Gate
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Installation of Dependencies and Execute Tests
        env:
          # Workaround to force usage of scoop apps installed in $env:USERPROFILE
          USER_PATH_FIRST: 1
        run: |
          .\build.ps1 -install
          pytest
        shell: powershell
      - name: Deploy Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          retention-days: 90
          path: |
            build/**/*.7z
            build/**/pr_changes.json
          if-no-files-found: error
