name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.variant }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        variant:
          - "BaseDev"
          - "BlinkLed"
          - "Disco"
          - "Sleep"
          - "Spa"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Installation of Dependencies and Execute Tests for ${{ matrix.variant }}
        run: |
          .\build.ps1 -install
          pytest -k "Test_${{ matrix.variant }}"
        shell: powershell
